const socket = require('../loaders/socket')
const Device = require('../models/device')
const usb = require('../utilities/usb')
const pythonRunner = require('../utilities/pythonRunner')
const handleInit = require('./handleInit')
const handleUpdateInfo = require('./handleUpdateInfo')
const handleStartStream = require('./handleStartStream')
const handleStartCast = require('./handleStartCast')
const handleStop = require('./handleStop')
module.exports = async () => {
    usb('add')
    usb('remove')
    handleInit(socket,pythonRunner,Device)
    handleUpdateInfo(socket,pythonRunner,Device)
    handleStartStream(socket,pythonRunner,Device)
    handleStartCast(socket,pythonRunner,Device)
    handleStop(socket,pythonRunner,Device)
} 